### ISSUE TITLE
ERROR: Failed to get kubeconfig

### ISSUE THREAD

**Issue by TylerLu** [jenkinsci/azure-acs-plugin#10] opened 2018-01-06 07:55 UTC
It worked correctly yesterday. But today I got an error on a totally new Jenkins server:
> Starting Azure Container Service / Kubernetes Service Deployment
Delete Kubernetes management config file /var/lib/jenkins/workspace/basic-docker-build/kubeconfig-3508984190195127281
ERROR: ERROR: Failed to get kubeconfig
java.lang.IllegalStateException: Failed to get kubeconfig
	at com.microsoft.jenkins.acs.commands.AKSDeploymentCommand$AKSDeployWorker.prepareKubeconfig(AKSDeploymentCommand.java:74)
	at com.microsoft.jenkins.acs.commands.KubernetesDeploymentCommandBase$KubernetesDeployWorker.call(KubernetesDeploymentCommandBase.java:170)
	...
ERROR: Azure Container Service / Kubernetes Service deployment ended with HasError

The Jenkins server was installed by the ARM Template: 
    [https://azure.microsoft.com/en-us/resources/templates/201-jenkins-acr/](https://azure.microsoft.com/en-us/resources/templates/201-jenkins-acr/)

Plugin version: 0.2.0

**Comment by ArieShout** [comment] 2018-01-08 02:13
This issue is not caused by the plugin.

The AKS does not expose the Kubernetes auth properties through Azure resource API now, so we cannot get the kubeconfig out of it. I'm checking with the AKS dev team on the issue and will update the status here.

Thanks for reporting the issue!

**Comment by TylerLu** [comment] 2018-01-08 05:30
@ArieShout Thanks for the response :)

I just checked the Azure resource API, and found that **kubeconfig** could be got with the [Get Managed Cluster API](https://docs.microsoft.com/en-us/rest/api/aks/managedclusters/getaccessprofiles#Examples).

> GET: https:// management.azure.com/subscriptions/*subid1*/resourceGroups/*rg1*/providers/Microsoft.ContainerService/managedClusters/*cluster1*/**accessProfiles/clusterUser**?api-version=2017-08-31

> Response: 
{
  "id": "/subscriptions/subid1/resourcegroups/rg1/providers/Microsoft.ContainerService/managedClusters/clustername1/accessProfiles/clusterUser",
  "location": "location1",
  "name": "clusterUser",
  "properties": {
    "**kubeConfig**": "kubeConfig1"
  },
  "type": "Microsoft.ContainerService/ManagedClusters/AccessProfiles"
}

It should be a breaking change which caused this issue. 

Hope it could help.

**Comment by ArieShout** [comment] 2018-01-09 04:10
@TylerLu Yes, got confirmed from AKS team the kubeconfig details was moved to the `accessProfiles` subresource to keep the top level resource clean.

I'm implementing the fix.

Thanks!

**Comment by TylerLu** [comment] 2018-01-09 04:21
@ArieShout Great! Thanks for the quick response.

**Comment by ArieShout** [comment] 2018-01-09 09:37
This should be fixed in https://github.com/jenkinsci/azure-acs-plugin/releases/tag/azure-acs-0.2.1.

@TylerLu please wait for some time before it shows up in the Jenkins update center.

**Comment by TylerLu** [comment] 2018-01-09 12:36
@ArieShout 👍 Thanks a lot!

**Closed** 2018-01-09 12:54 UTC
Labels: bug
