### ISSUE TITLE
ERROR: null exception in GenericResourcesImpl.getById

### ISSUE THREAD

**Issue by ondrejmichlicekips** [jenkinsci/azure-acs-plugin#16] opened 2019-02-04 16:16 UTC
Build worked correctly till 31st of January 2019. Then without any modification it started to throw following error:
--------------------------------------------------
```
Started by user admin
Running in Durability level: MAX_SURVIVABILITY
[Pipeline] Start of Pipeline
[Pipeline] stage
[Pipeline] { (Test Deploy)
[Pipeline] node
Running on Jenkins in C:\Program Files (x86)\Jenkins\workspace\Test_project\AKS_Test
[Pipeline] {
[Pipeline] acsDeploy
Starting Azure Container Service / Kubernetes Service Deployment
Delete Kubernetes management config file C:\Program Files (x86)\Jenkins\workspace\Test_project\AKS_Test\kubeconfig-4637128700832550368
ERROR: ERROR: null
java.lang.NullPointerException
	at com.microsoft.azure.management.resources.implementation.GenericResourcesImpl.getById(GenericResourcesImpl.java:92)
	at com.microsoft.azure.management.resources.implementation.GenericResourcesImpl.getById(GenericResourcesImpl.java:28)
	at com.microsoft.jenkins.acs.commands.AKSDeploymentCommand$AKSDeployWorker.prepareKubeconfig(AKSDeploymentCommand.java:62)
	at com.microsoft.jenkins.acs.commands.KubernetesDeploymentCommandBase$KubernetesDeployWorker.call(KubernetesDeploymentCommandBase.java:170)
	at com.microsoft.jenkins.acs.commands.KubernetesDeploymentCommandBase$KubernetesDeployWorker.call(KubernetesDeploymentCommandBase.java:133)
	at hudson.FilePath.act(FilePath.java:1165)
	at com.microsoft.jenkins.acs.commands.KubernetesDeploymentCommandBase.doExecute(KubernetesDeploymentCommandBase.java:79)
	at com.microsoft.jenkins.acs.commands.AKSDeploymentCommand.execute(AKSDeploymentCommand.java:37)
	at com.microsoft.jenkins.acs.commands.AKSDeploymentCommand.execute(AKSDeploymentCommand.java:25)
...
ERROR: Azure Container Service / Kubernetes Service deployment ended with HasError
Finished: FAILURE
```
--------------------------------------------------

By the code inspection it looks like problem with Azure/AKS API.

acsDeploy 0.2.3
Jenkins 2.150.2

**Comment by kristianhald** [comment] 2019-02-05 10:03
We are having the same problem with out AKS setup. ACI is working without problems. 
Ours started failing yesterday morning and our AKS is running in Azure WestEurope.

We are using 'Azure Container Agents Plugin' version 0.4.1 and Jenkins is 2.163.
We have not made any changes to our setup prior to the failure.

I believe AKS API might have been updated. 
Written a ticket to Microsoft yesterday to determine if this is the case.

**Comment by jcme** [comment] 2019-02-05 11:40
We're experiencing the same issue as well, currently unable to complete any deployments

Azure Container Service Plugin version 0.2.3
Jenkins version 2.150.2

`[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Deploy)
[Pipeline] acsDeploy
Starting Azure Container Service / Kubernetes Service Deployment
ERROR: ERROR: null
java.lang.NullPointerException
	at com.microsoft.azure.management.resources.implementation.GenericResourcesImpl.getById(GenericResourcesImpl.java:92)
	at com.microsoft.azure.management.resources.implementation.GenericResourcesImpl.getById(GenericResourcesImpl.java:28)
	at com.microsoft.jenkins.acs.commands.AKSDeploymentCommand$AKSDeployWorker.prepareKubeconfig(AKSDeploymentCommand.java:62)
	at com.microsoft.jenkins.acs.commands.KubernetesDeploymentCommandBase$KubernetesDeployWorker.call(KubernetesDeploymentCommandBase.java:170)
	at com.microsoft.jenkins.acs.commands.KubernetesDeploymentCommandBase$KubernetesDeployWorker.call(KubernetesDeploymentCommandBase.java:133)
	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:844)
	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to jenkins-linux-node-nodejs
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
		at hudson.remoting.Channel.call(Channel.java:955)
		at hudson.FilePath.act(FilePath.java:1162)
		at com.microsoft.jenkins.acs.commands.KubernetesDeploymentCommandBase.doExecute(KubernetesDeploymentCommandBase.java:79)
		at com.microsoft.jenkins.acs.commands.AKSDeploymentCommand.execute(AKSDeploymentCommand.java:37)
		at com.microsoft.jenkins.acs.commands.AKSDeploymentCommand.execute(AKSDeploymentCommand.java:25)
		at com.microsoft.jenkins.azurecommons.command.CommandService.runCommand(CommandService.java:88)
		at com.microsoft.jenkins.azurecommons.command.CommandService.execute(CommandService.java:96)
		at com.microsoft.jenkins.azurecommons.command.CommandService.executeCommands(CommandService.java:75)
		at com.microsoft.jenkins.azurecommons.command.BaseCommandContext.executeCommands(BaseCommandContext.java:77)
		at com.microsoft.jenkins.acs.ACSDeploymentBuilder.perform(ACSDeploymentBuilder.java:56)
		at com.microsoft.jenkins.acs.ACSDeploymentContext$ExecutionImpl.run(ACSDeploymentContext.java:141)
		at com.microsoft.jenkins.acs.ACSDeploymentContext$ExecutionImpl.run(ACSDeploymentContext.java:125)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:748)
[Pipeline] }
[Pipeline] // stage`

**Comment by BartSaelen** [comment] 2019-02-05 14:46
We are experiencing the same problem, since last friday.

```
ERROR: ERROR: null
java.lang.NullPointerException
	at com.microsoft.azure.management.resources.implementation.GenericResourcesImpl.getById(GenericResourcesImpl.java:92)
	at com.microsoft.azure.management.resources.implementation.GenericResourcesImpl.getById(GenericResourcesImpl.java:28)
	at com.microsoft.jenkins.acs.commands.AKSDeploymentCommand$AKSDeployWorker.prepareKubeconfig(AKSDeploymentCommand.java:62)
	at com.microsoft.jenkins.acs.commands.KubernetesDeploymentCommandBase$KubernetesDeployWorker.call(KubernetesDeploymentCommandBase.java:170)
	at com.microsoft.jenkins.acs.commands.KubernetesDeploymentCommandBase$KubernetesDeployWorker.call(KubernetesDeploymentCommandBase.java:133)
	at hudson.FilePath.act(FilePath.java:1165)
	at com.microsoft.jenkins.acs.commands.KubernetesDeploymentCommandBase.doExecute(KubernetesDeploymentCommandBase.java:79)
	at com.microsoft.jenkins.acs.commands.AKSDeploymentCommand.execute(AKSDeploymentCommand.java:37)
	at com.microsoft.jenkins.acs.commands.AKSDeploymentCommand.execute(AKSDeploymentCommand.java:25)
	at com.microsoft.jenkins.azurecommons.command.CommandService.runCommand(CommandService.java:88)
	at com.microsoft.jenkins.azurecommons.command.CommandService.execute(CommandService.java:96)
	at com.microsoft.jenkins.azurecommons.command.CommandService.executeCommands(CommandService.java:75)
	at com.microsoft.jenkins.azurecommons.command.BaseCommandContext.executeCommands(BaseCommandContext.java:77)
	at com.microsoft.jenkins.acs.ACSDeploymentBuilder.perform(ACSDeploymentBuilder.java:56)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.Build$BuildExecution.build(Build.java:206)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1810)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
ERROR: Azure Container Service / Kubernetes Service deployment ended with HasError
Finished: FAILURE
```

Jenkins ver. 2.150.2
Azure Container Service Plugin ver. 0.2.3

**Comment by tomaszszlek** [comment] 2019-02-05 17:58
I am facing the same issue, in K8s logs I can see the following :

**Operation name**
Get Managed Cluster AccessProfile by List Credential

`Could not find role name: clusterAdmin in subscription: xxxx, resourceGroup: MyResourceGroup, managed cluster resource: k8s.`

**Comment by weinong** [comment] 2019-02-05 23:20
the accessProfile resource is not versioned as managed cluster resource.. the proper way is to use the POST command instead. Rest API reference: https://docs.microsoft.com/en-us/rest/api/aks/managedclusters/listclusteradmincredentials

**Comment by widgetpl** [comment] 2019-02-06 14:52
so Jenkins plugin uses Azure libs for Java and it reference to this
[GenericResourcesImpl.java](https://github.com/Azure/azure-libraries-for-java/blob/master/azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/implementation/GenericResourcesImpl.java#L89)
[ResourcesInner.java](https://github.com/Azure/azure-libraries-for-java/blob/master/azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/implementation/ResourcesInner.java#L154)
```
        @Headers({ "Content-Type: application/json; charset=utf-8", "x-ms-logging-context: com.microsoft.azure.management.resources.Resources getById" })
        @GET("{resourceId}")
        Observable<Response<ResponseBody>> getById(@Path(value = "resourceId", encoded = true) String resourceId, @Query("api-version") String apiVersion, @Header("accept-language") String acceptLanguage, @Header("User-Agent") String userAgent);
```
so `GET` is used but still the question is what has changed as this used to work

**Comment by yangl900** [comment] 2019-02-06 23:23
AKS published a new API version (2018-08-01-preview), and it seems the Jenkins plugin dynamically discovers and uses the latest API version. This caused the problem because the GET /accessProfiles API is intend to be deprecated in newer versions. A hotfix is on the way to mitigate the issue..

**Comment by weinong** [comment] 2019-02-07 21:29
@widgetpl the proper API is to use List{Admin|ClusterUser}Credentials like https://github.com/Azure/azure-libraries-for-java/blob/b4caebe92d042fddb59277945c76a69c4b224a52/azure-mgmt-containerservice/src/main/java/com/microsoft/azure/management/containerservice/implementation/ManagedClustersInner.java#L555

**Comment by ps-rfriesen** [comment] 2019-02-08 09:18
@yangl900 Hi,
as we are eagerly waiting for that fix, to get our deployment pipeline running again, could you please indicate where the information the a hotfix is on the way is coming from. I couldn't find any information regarding that except for the comment here.

Thanks in advance

**Comment by amitnanaware** [comment] 2019-02-12 09:52
> AKS published a new API version (2018-08-01-preview), and it seems the Jenkins plugin dynamically discovers and uses the latest API version. This caused the problem because the GET /accessProfiles API is intend to be deprecated in newer versions. A hotfix is on the way to mitigate the issue..

We are also facing same issue since last few days? When we can expect fix on this?

**Comment by kristianhald** [comment] 2019-02-12 10:06
@amitnanaware Still having the error? 

I believe this error is the same, that we have had with the Azure Container Agents plugin. Azure deployed a hotfix to AKS to mitigate this error. 

https://github.com/Azure/AKS/releases/tag/2019-02-07

**Comment by jcme** [comment] 2019-02-12 10:13
Seems to have resolved the issue for us. Thanks all!

**Comment by amitnanaware** [comment] 2019-02-12 11:28
> @amitnanaware Still having the error?
> 
> I believe this error is the same, that we have had with the Azure Container Agents plugin. Azure deployed a hotfix to AKS to mitigate this error.
> 
> https://github.com/Azure/AKS/releases/tag/2019-02-07

The issue is resolved thanks!

**Comment by amenon90** [comment] 2019-04-04 08:45
I think this has resurfaced. My deployments were working fine, and today I started getting this:
```
Starting Azure Container Service / Kubernetes Service Deployment
Delete Kubernetes management config file /home/deploy/workspace/project/kubeconfig-6074144939093463942
ERROR: ERROR: null
java.lang.NullPointerException
	at com.microsoft.azure.management.resources.implementation.GenericResourcesImpl.getById(GenericResourcesImpl.java:92)
	at com.microsoft.azure.management.resources.implementation.GenericResourcesImpl.getById(GenericResourcesImpl.java:28)
	at com.microsoft.jenkins.acs.commands.AKSDeploymentCommand$AKSDeployWorker.prepareKubeconfig(AKSDeploymentCommand.java:62)
	at com.microsoft.jenkins.acs.commands.KubernetesDeploymentCommandBase$KubernetesDeployWorker.call(KubernetesDeploymentCommandBase.java:170)
	at com.microsoft.jenkins.acs.commands.KubernetesDeploymentCommandBase$KubernetesDeployWorker.call(KubernetesDeploymentCommandBase.java:133)
	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to dotnetffb800
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
		at hudson.remoting.Channel.call(Channel.java:955)
		at hudson.FilePath.act(FilePath.java:1160)
		at com.microsoft.jenkins.acs.commands.KubernetesDeploymentCommandBase.doExecute(KubernetesDeploymentCommandBase.java:79)
		at com.microsoft.jenkins.acs.commands.AKSDeploymentCommand.execute(AKSDeploymentCommand.java:37)
		at com.microsoft.jenkins.acs.commands.AKSDeploymentCommand.execute(AKSDeploymentCommand.java:25)
		at com.microsoft.jenkins.azurecommons.command.CommandService.runCommand(CommandService.java:88)
		at com.microsoft.jenkins.azurecommons.command.CommandService.execute(CommandService.java:96)
		at com.microsoft.jenkins.azurecommons.command.CommandService.executeCommands(CommandService.java:75)
		at com.microsoft.jenkins.azurecommons.command.BaseCommandContext.executeCommands(BaseCommandContext.java:77)
		at com.microsoft.jenkins.acs.ACSDeploymentBuilder.perform(ACSDeploymentBuilder.java:56)
		at com.microsoft.jenkins.acs.ACSDeploymentContext$ExecutionImpl.run(ACSDeploymentContext.java:141)
		at com.microsoft.jenkins.acs.ACSDeploymentContext$ExecutionImpl.run(ACSDeploymentContext.java:125)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:50)
		at hudson.security.ACL.impersonate(ACL.java:290)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:47)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		... 4 more
```

**Comment by jcme** [comment] 2019-04-04 08:58
Yes, seems to be broken for us again as well:
```
Starting Azure Container Service / Kubernetes Service Deployment

ERROR: ERROR: null

java.lang.NullPointerException

	at com.microsoft.azure.management.resources.implementation.GenericResourcesImpl.getById(GenericResourcesImpl.java:92)

	at com.microsoft.azure.management.resources.implementation.GenericResourcesImpl.getById(GenericResourcesImpl.java:28)

	at com.microsoft.jenkins.acs.commands.AKSDeploymentCommand$AKSDeployWorker.prepareKubeconfig(AKSDeploymentCommand.java:62)

	at com.microsoft.jenkins.acs.commands.KubernetesDeploymentCommandBase$KubernetesDeployWorker.call(KubernetesDeploymentCommandBase.java:170)

	at com.microsoft.jenkins.acs.commands.KubernetesDeploymentCommandBase$KubernetesDeployWorker.call(KubernetesDeploymentCommandBase.java:133)

	at hudson.remoting.UserRequest.perform(UserRequest.java:212)

	at hudson.remoting.UserRequest.perform(UserRequest.java:54)

	at hudson.remoting.Request$2.run(Request.java:369)

	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)

	at java.util.concurrent.FutureTask.run(FutureTask.java:264)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)

	at java.lang.Thread.run(Thread.java:844)

	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to jenkins-linux-node-nodejs

		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)

		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)

		at hudson.remoting.Channel.call(Channel.java:955)

		at hudson.FilePath.act(FilePath.java:1162)

		at com.microsoft.jenkins.acs.commands.KubernetesDeploymentCommandBase.doExecute(KubernetesDeploymentCommandBase.java:79)

		at com.microsoft.jenkins.acs.commands.AKSDeploymentCommand.execute(AKSDeploymentCommand.java:37)

		at com.microsoft.jenkins.acs.commands.AKSDeploymentCommand.execute(AKSDeploymentCommand.java:25)

		at com.microsoft.jenkins.azurecommons.command.CommandService.runCommand(CommandService.java:88)

		at com.microsoft.jenkins.azurecommons.command.CommandService.execute(CommandService.java:96)

		at com.microsoft.jenkins.azurecommons.command.CommandService.executeCommands(CommandService.java:75)

		at com.microsoft.jenkins.azurecommons.command.BaseCommandContext.executeCommands(BaseCommandContext.java:77)

		at com.microsoft.jenkins.acs.ACSDeploymentBuilder.perform(ACSDeploymentBuilder.java:56)

		at com.microsoft.jenkins.acs.ACSDeploymentContext$ExecutionImpl.run(ACSDeploymentContext.java:141)

		at com.microsoft.jenkins.acs.ACSDeploymentContext$ExecutionImpl.run(ACSDeploymentContext.java:125)

		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)

		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

		at java.util.concurrent.FutureTask.run(FutureTask.java:266)

		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

		at java.lang.Thread.run(Thread.java:748)
```

**Comment by ondrejmichlicekips** [comment] 2019-04-04 09:03
Confirm, that issue is back. Probably new API rollout :(

**Comment by szymon-wlodarczyk** [comment] 2019-04-04 11:47
Same for me

**Comment by FrankGNL** [comment] 2019-04-04 12:15
Same problems here since this morning Amsterdam time

**Comment by dipalpatel** [comment] 2019-04-04 12:54
This keeps coming back. We need to find the fix on our own rather than rely on them.

**Comment by sureshselvam01** [comment] 2019-04-04 12:55
Same issue here too. When could we expect the fix

**Comment by jeffmartinxyz** [comment] 2019-04-04 20:15
@weinong

**Comment by szymon-wlodarczyk** [comment] 2019-04-08 07:34
Hello, issue is still occurring, when we can expect fix for this ?

**Comment by gavinfish** [comment] 2019-04-09 05:59
I am working on fixing this issue. A PR is on the way.

**Closed** 2019-04-09 07:47 UTC

**Comment by szymon-wlodarczyk** [comment] 2019-04-09 07:49
when new plugin version will be released with this fix ?

**Comment by gavinfish** [comment] 2019-04-09 07:56
I am now working on the release process, the new version will be 0.2.4 thanks.

**Comment by amenon90** [comment] 2019-04-09 12:18
0.2.4 works. Thank you very much @gavinfish
